/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petroms;

import DBMS.Customer;
import DBMS.DBMS_Customer;
import DBMS.Person;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class frmAddCustomer extends javax.swing.JPanel {

    private DefaultTableModel model ; 
    private DBMS_Customer dbc ;
    
    public frmAddCustomer() {
        initComponents();
           
    }
    
    public frmAddCustomer(DBMS_Customer dbc){
        this.initComponents();
        
        setCulumn();
        this.dbc = dbc;
        this.Display_data_table(dbc.getAllCustomer());
        this.txtid.setText("CSPS "+(dbc.getSize()+1));
        txtid.setEnabled(false);
        setEnableButton(2);
    }
    private void setEnableButton(int i){
        if(i==1){
            btadd.setEnabled(false);
            btupdate.setEnabled(true);
            btdelet.setEnabled(true);
        }else{
            btadd.setEnabled(true);
            btupdate.setEnabled(false);
            btdelet.setEnabled(false);

        }
    }
    private void setCulumn(){
        model = (DefaultTableModel)t.getModel();
        //--- setColumn width
        t.getColumnModel().getColumn(0).setPreferredWidth(2);
        t.getColumnModel().getColumn(1).setPreferredWidth(50);
        t.getColumnModel().getColumn(2).setPreferredWidth(100);
        t.getColumnModel().getColumn(3).setPreferredWidth(10);
        t.getColumnModel().getColumn(4).setPreferredWidth(100);
        //t.getColumnModel().getColumn(6).setPreferredWidth();
    }
    //------
    
    private void  Display_data_table(ArrayList<Customer> d){
       // remove data from table
       int rc = t.getRowCount();
       int n = 1;
       for(int i = rc -1 ; i>=0 ; i--)
           model.removeRow(i);
       //--- data to table
       for(Customer c : d){
           model.addRow(new Object[]{n,c.getID(),c.getName(),c.getSex(),
           c.getStation_name(),c.getAdress(),c.getPhone()});
           n++;
       }
       t.setModel(model);
    }
    
    //---- Check Texbox----
    private Customer checkTextBox(){
        String id = txtid.getText();
        String name = txtname.getText();
        String sex = cbosex.getSelectedItem().toString();
        String station_name = this.txtstation_name.getText();
        String address = this.txtaddress.getText();
        String phone = this.txtphone.getText();
        
        if(id.length()==0)
            Msg(txtid,"Input ID ");
        else if(name.length()==0)
            Msg(txtname,"Input Name");
        else if(station_name.length()==0)
            Msg(txtstation_name,"Input Station Name");
        else if(address.length()==0)
            Msg(txtaddress,"Input Address");
        else if(phone.length()==0)
            Msg(txtphone,"Input phone number");
        else{
            return new Customer(new Person(id,name,sex),station_name,address,phone);
        }     
        return null;
    }//
    //---- setFocus when textfield if empty
    private void Msg(JTextField t,String mess){
        JOptionPane.showMessageDialog(null, mess);
        t.requestFocus();
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbosex = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtstation_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnew = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        btupdate = new javax.swing.JButton();
        btdelet = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("ADD NEW CUSTOMER");

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Sex");

        cbosex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel5.setText("Station");

        jLabel6.setText("Address");

        jLabel7.setText("Phone");

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        btnew.setText("New");
        btnew.setPreferredSize(new java.awt.Dimension(100, 31));
        btnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnewMouseClicked(evt);
            }
        });
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        btadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        btadd.setText("ADD");
        btadd.setPreferredSize(new java.awt.Dimension(100, 31));
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shearch.png"))); // NOI18N

        txtsearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsearchCaretUpdate(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Name", "Sex", "Station", "Address", "Phone"
            }
        ));
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t);

        btupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        btupdate.setText("Update");
        btupdate.setPreferredSize(new java.awt.Dimension(100, 31));
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        btdelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btdelet.setText("Delete");
        btdelet.setPreferredSize(new java.awt.Dimension(100, 31));
        btdelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btdelet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(txtid))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(txtstation_name))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbosex, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbosex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtstation_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdelet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        Customer c = checkTextBox();
        if(dbc.getCus_ID_Index(txtid.getText())!=-1){
            JOptionPane.showMessageDialog(null,"Already exist "+ txtid.getText());
            txtid.setEnabled(true);
            return;
        }
         if(c!=null){
             int rs = JOptionPane.showConfirmDialog(null, "Add one record","Add new Record",
                     JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
             if(rs==0){
               dbc.addCustomer(c);
               model.addRow(new Object[]{t.getRowCount()+1,c.getID(),
               c.getName(),c.getSex(),c.getStation_name(),c.getAdress(),c.getPhone()});
               t.setModel(model);
               txtid.setEnabled(false);
               ClearText();
                 
             }
             
         }
                
    }//GEN-LAST:event_btaddActionPerformed
    private void ClearText(){
        this.txtaddress.setText("");
               this.txtphone.setText("");
               this.txtstation_name.setText("");
               this.txtid.setText("CSPS "+(dbc.getSize()+1));
               txtname.selectAll();
               txtname.requestFocus();
    }
    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:   
        Customer c = this.checkTextBox();
        if(c==null)return;
        this.setEnableButton(2);
        int y = JOptionPane.showConfirmDialog(null, "Do you want to update this recor",
                "Update for",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(y==0){
           
               int sr = t.getSelectedRow();
               int i = dbc.getCus_ID_Index(c.getID());
               
               dbc.updateCustomer(i, c);
               
               t.setValueAt(c.getID(), sr, 1);
               t.setValueAt(c.getName(), sr, 2);
               t.setValueAt(c.getSex(), sr, 3);
               t.setValueAt(c.getStation_name(), sr, 4);
               t.setValueAt(c.getAdress(), sr, 5);
               t.setValueAt(c.getPhone(), sr, 6);
           
        }
        ClearText();
                
    }//GEN-LAST:event_btupdateActionPerformed

    private void btdeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeletActionPerformed
        // TODO add your handling code here:
        int rs = t.getSelectedRow();
        int y = JOptionPane.showConfirmDialog(null, "Do you want to update this recor",
                "Update for",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(y==0){
            dbc.removeCustomer(rs);
            model.removeRow(rs);
            this.setEnableButton(2);
            this.ClearText();
        }
    }//GEN-LAST:event_btdeletActionPerformed

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        this.setEnableButton(1);
        int rs = dbc.getCus_ID_Index(t.getValueAt(t.getSelectedRow(), 1).toString());
        if(rs!=-1){
        
           Customer c = (Customer)dbc.getCustomer(rs);
           txtid.setText(c.getID());
           txtname.setText(c.getName());
           cbosex.setSelectedItem(c.getSex());
           txtstation_name.setText(c.getStation_name());
           txtaddress.setText(c.getAdress());
           txtphone.setText(c.getPhone());
        }
        
    }//GEN-LAST:event_tMouseClicked

    private void btnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnewMouseClicked
        // TODO add your handling code here:
        setEnableButton(2);
        this.ClearText();
    }//GEN-LAST:event_btnewMouseClicked

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnewActionPerformed

    private void txtsearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsearchCaretUpdate
        // TODO add your handling code here:
        this.Display_data_table(dbc.getFilterName(txtsearch.getText()));
    }//GEN-LAST:event_txtsearchCaretUpdate

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelet;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox<String> cbosex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable t;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstation_name;
    // End of variables declaration//GEN-END:variables
}
