/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petroms;

import DBMS.DBMS_Customer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author senghak
 */
public class frmMain extends javax.swing.JFrame {

    private boolean back= true;
    private int add = 0;
    private DBMS_Customer db = new DBMS_Customer("Petrol.txt");
    //--- setcolor
    
    private final ArrayList<JLabel> lis = new ArrayList();
    public frmMain() {
        initComponents();
        //--
        
        //--
        
        this.setSize(1300, 700);
        this.setLocationRelativeTo(null);
        lis.add(this.lblAdd);
        lis.add(this.lblSal);
        lis.add(this.lblReport);
        lis.add(this.lblReportOrder);
        lis.add(this.lblReportSaler);
        //loadform.interface 
        this.refresh(new p_home() );
        
    }

    //----- refresh form
    private void refresh( JPanel load){
       pcontance.removeAll();
       pcontance.add(load);       
       pcontance.validate();
       load.setVisible(true);       
    }
    //--- mouse over
      private void MousOver(int i,ArrayList<JLabel>l){
          for(int j =0 ; j<l.size();j++){
              
              if(j==i){
                  l.get(j).setForeground(Color.red);
                  l.get(j).setFont(new Font("",Font.ITALIC,12));
              }
              else{
                  l.get(j).setForeground(Color.white);
                  l.get(j).setFont(new Font("",Font.BOLD,12));
              }
                
          }// end loop          
      }
      //--- end function
     
    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnaviga = new javax.swing.JPanel();
        pback = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbladdcustomer = new javax.swing.JLabel();
        lblsale = new javax.swing.JLabel();
        lblreport = new javax.swing.JLabel();
        paddcustomer = new javax.swing.JPanel();
        lblAdd = new javax.swing.JLabel();
        paddcustomer1 = new javax.swing.JPanel();
        paddcustomer2 = new javax.swing.JPanel();
        lblReport = new javax.swing.JLabel();
        preport = new javax.swing.JPanel();
        lblReportOrder = new javax.swing.JLabel();
        lblReportSaler = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        pcontance = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(500, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnaviga.setBackground(new java.awt.Color(0, 102, 102));
        pnaviga.setPreferredSize(new java.awt.Dimension(180, 610));

        pback.setBackground(new java.awt.Color(0, 153, 102));
        pback.setAlignmentX(0.0F);
        pback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbackMouseClicked(evt);
            }
        });

        lblback.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        lblback.setPreferredSize(new java.awt.Dimension(25, 25));
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pbackLayout = new javax.swing.GroupLayout(pback);
        pback.setLayout(pbackLayout);
        pbackLayout.setHorizontalGroup(
            pbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbackLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbackLayout.setVerticalGroup(
            pbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblback, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));

        lbladdcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N

        lblsale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sale.png"))); // NOI18N

        lblreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minus.png"))); // NOI18N
        lblreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblreportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdcustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblsale, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblreport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbladdcustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblreport)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        paddcustomer.setBackground(new java.awt.Color(0, 102, 102));
        paddcustomer.setLayout(new java.awt.BorderLayout());

        lblAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("ADD CUSTOMER");
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddMouseEntered(evt);
            }
        });
        paddcustomer.add(lblAdd, java.awt.BorderLayout.CENTER);

        paddcustomer1.setBackground(new java.awt.Color(0, 102, 102));
        paddcustomer1.setLayout(new java.awt.BorderLayout());

        paddcustomer2.setBackground(new java.awt.Color(0, 102, 102));
        paddcustomer2.setPreferredSize(new java.awt.Dimension(118, 18));
        paddcustomer2.setLayout(new java.awt.BorderLayout());

        lblReport.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setText("REPORT");
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
        });
        paddcustomer2.add(lblReport, java.awt.BorderLayout.CENTER);

        preport.setBackground(new java.awt.Color(0, 102, 102));
        preport.setPreferredSize(new java.awt.Dimension(118, 62));

        lblReportOrder.setBackground(new java.awt.Color(255, 255, 255));
        lblReportOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblReportOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblReportOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReportOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        lblReportOrder.setText("ORDER");
        lblReportOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportOrderMouseEntered(evt);
            }
        });

        lblReportSaler.setBackground(new java.awt.Color(255, 255, 255));
        lblReportSaler.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblReportSaler.setForeground(new java.awt.Color(255, 255, 255));
        lblReportSaler.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReportSaler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        lblReportSaler.setText("SALER");
        lblReportSaler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportSalerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout preportLayout = new javax.swing.GroupLayout(preport);
        preport.setLayout(preportLayout);
        preportLayout.setHorizontalGroup(
            preportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReportSaler, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        preportLayout.setVerticalGroup(
            preportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preportLayout.createSequentialGroup()
                .addComponent(lblReportOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportSaler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log.png"))); // NOI18N

        lblSal.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblSal.setForeground(new java.awt.Color(255, 255, 255));
        lblSal.setText("SALE");
        lblSal.setPreferredSize(new java.awt.Dimension(35, 18));
        lblSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnavigaLayout = new javax.swing.GroupLayout(pnaviga);
        pnaviga.setLayout(pnavigaLayout);
        pnavigaLayout.setHorizontalGroup(
            pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnavigaLayout.createSequentialGroup()
                .addGroup(pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnavigaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnavigaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(preport, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                            .addGroup(pnavigaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paddcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnavigaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblSal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnavigaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(paddcustomer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paddcustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnavigaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnavigaLayout.setVerticalGroup(
            pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnavigaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnavigaLayout.createSequentialGroup()
                        .addComponent(paddcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lblSal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnavigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paddcustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paddcustomer2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pcontance.setBackground(new java.awt.Color(255, 255, 255));
        pcontance.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnaviga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcontance, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnaviga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pcontance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        // TODO add your handling code here:
        if(back == true){
            this.pnaviga.setPreferredSize(new Dimension(50,this.getHeight()));
            lblback.setIcon(new ImageIcon(getClass().getResource("/image/f.png")));
            SwingUtilities.updateComponentTreeUI(this);
            back = false;
        }else{
           this.pnaviga.setPreferredSize(new Dimension(180,this.getHeight()));
            lblback.setIcon(new ImageIcon(getClass().getResource("/image/back.png")));
            SwingUtilities.updateComponentTreeUI(this);
            back = true;
 
        }

    }//GEN-LAST:event_lblbackMouseClicked

    private void lblreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreportMouseClicked
        // TODO add your handling code here:
        if(add == 1){
            this.preport.setPreferredSize(new Dimension(100,60));
            lblreport.setIcon(new ImageIcon(getClass().getResource("/image/minus.png")));
            SwingUtilities.updateComponentTreeUI(this);
            add = 0;
        }else{
           this.preport.setPreferredSize(new Dimension(0,0));
            lblreport.setIcon(new ImageIcon(getClass().getResource("/image/add.png")));
            SwingUtilities.updateComponentTreeUI(this);
            add = 1;
 
        }

    }//GEN-LAST:event_lblreportMouseClicked

    private void lblAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseEntered
        // TODO add your handling code here:
        this.MousOver(0, lis);
        
        
    }//GEN-LAST:event_lblAddMouseEntered

    private void lblSalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalMouseEntered
        // TODO add your handling code here:
        this.MousOver(1, lis);
    }//GEN-LAST:event_lblSalMouseEntered

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered
        // TODO add your handling code here:
        MousOver(2,lis);
    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportOrderMouseEntered
        // TODO add your handling code here:
        MousOver(3,lis);
    }//GEN-LAST:event_lblReportOrderMouseEntered

    private void lblReportSalerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportSalerMouseEntered
        // TODO add your handling code here:
        MousOver(4,lis);
    }//GEN-LAST:event_lblReportSalerMouseEntered

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        // TODO add your handling code here:
        this.lblreportMouseClicked(evt);
        
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        // TODO add your handling code here:
        this.refresh(new frmAddCustomer(db));
    }//GEN-LAST:event_lblAddMouseClicked

    private void pbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbackMouseClicked
        // TODO add your handling code here:
        refresh(new p_home());
    }//GEN-LAST:event_pbackMouseClicked

    private void lblSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalMouseClicked
        // TODO add your handling code here:
        refresh(new frmSale());
    }//GEN-LAST:event_lblSalMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        db.InsertDataToFile();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReportOrder;
    private javax.swing.JLabel lblReportSaler;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lbladdcustomer;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblreport;
    private javax.swing.JLabel lblsale;
    private javax.swing.JPanel paddcustomer;
    private javax.swing.JPanel paddcustomer1;
    private javax.swing.JPanel paddcustomer2;
    private javax.swing.JPanel pback;
    private javax.swing.JPanel pcontance;
    private javax.swing.JPanel pnaviga;
    private javax.swing.JPanel preport;
    // End of variables declaration//GEN-END:variables
}
